[package]
name = "skyzen-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes  = "1.1.0"
http-kit = { git = "https://github.com/lexoooooo/http-kit.git", rev = "7733014"}
bytestr = "0.1.0" 
async-trait = "0.1.57"
futures-io = "0.3.23"
http = "0.2.8"
anyhow = "1.0.75"