[package]
name = "skyzen-hyper"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
skyzen = { path="../skyzen" }
tower-service = "0.3.2"

[dependencies.hyper]
version = "0.14.20"
default-features = false 
features = ["server","stream","tcp","http1","http2"]